package de.hebk;

import java.util.Random;

public class Texts {

    private Random r1 = new Random();
    private int r2 = r1.nextInt(14);

    public String[] csvFiles_Questions = {
            "Allgemein",
            "Geschichte",
            "Natur-Pflanzen",
            "Physik",
            "Sport",
            "Videospiele",
            "Chemie",
            "Tierwelt",
    };

    public String[] currencies = {
            "$",
            "€",
            "£",
            "¥",
            "₣",
            "₹",
            "د.ك",
            "د.إ",
            "﷼",
            "₻",
            "₽",
            "₾",
            "₺",
            "₼",
            "₸",
            "₴",
            "₷",
            "฿",
            "원",
            "₯",
            "₱",
            "₳",
            "₵",
            "₲",
            "₪",
            "₰",
    };

    public String[] values1 = {"100", "500", "2500", "10000", "25000", "75000", "150000", "250000", "500000", "1000000"};
    public String[] values2 = {"100", "250", "500", "1000", "2500", "5000", "7500", "10000", "25000", "50000", "100000", "150000", "250000", "500000", "1000000"};
    public String[] values3 = {"100", "150", "250", "500", "1000", "2500", "5000", "7500", "10000", "15000", "25000", "350000", "50000", "750000", "1000000", "150000", "225000", "350000", "500000", "1000000"};

    public String[] randomNames = {
            "Ter",
            "The",
            "Knight",
            "Shredder",
            "Zufälliger",
            "Lack",
            "Master",
            "Richtig",
            "Eins",
            "Name",
            "Element",
            "Null",
            "Keiner",
            "Echter",
            "Bester",
            "Ninja",
            "Zero",
            "Zufällig",
            "Destroyer",
            "_Laser",
            "Game",
            "Cube",
            "Core",
            "Neon",
            "Zahl",
            "Generic",
            "Funktion",
            "Code",
            "Winner",
            "Dust",
            "Nemesis",
            "Final Fantasy" + (r2 +1),
            "Terminator",
            "User",
            "Axe",
            "Lost",
            "High",
            "Java",
            "Geheim",
            "Ranger",
            "Raptor",
            "Akar",
            "Mars",
            "Rest",
            "Razor",
            "Zahl",
            "Yukin",
            "Bat",
            "Kämpfer",
            "Falle",
            "Rote",
            "Ista",
            "AusT",
            "InD_",
            "Rats",
            "Spike",
            "Klasse",
            "Abstrakte",
            "Fantasy",
            "Old School ",
            "Hero",
            "Lord",
            "Dark",
            "Void",
            "Reaper",
            "Invisible",
            "Monster",
            "Mana",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",

    };
}