package de.hebk;

import java.util.Random;

public class Texts {

    private Random r1 = new Random();
    private int r2 = r1.nextInt(14);

    public String[] csvFiles_Questions = {
            "Allgemein",
            "Geschichte",
            "Natur-Pflanzen",
            "Physik",
            "Sport",
            "Videospiele",
            "Chemie",
            "Tierwelt",
    };

    public String[] currencies = {
            "$",
            "€",
            "£",
            "¥",
            "₣",
            "₹",
            "د.ك",
            "د.إ",
            "﷼",
            "₻",
            "₽",
            "₾",
            "₺",
            "₼",
            "₸",
            "₴",
            "₷",
            "฿",
            "원",
            "₯",
            "₱",
            "₳",
            "₵",
            "₲",
            "₪",
            "₰",
    };

    public String[] values1 = {"100", "500", "2500", "10000", "25000", "75000", "150000", "250000", "500000", "1000000"};
    public String[] values2 = {"100", "250", "500", "1000", "2500", "5000", "7500", "10000", "25000", "50000", "100000", "150000", "250000", "500000", "1000000"};
    public String[] values3 = {"100", "150", "250", "500", "1000", "2500", "5000", "7500", "10000", "15000", "25000", "350000", "50000", "750000", "1000000", "150000", "225000", "350000", "500000", "1000000"};

    public String[] firstNames = {
            "Submissive",
            "IceOut",
            "Slay",
            "[They/Them]",
            "KissXSis",
            "SíSíPorFavores",
            "BetterThanYourEx",
            "Dark",
            "Horny",
            "Big",
            "Eigentlich...",
            "Bad",
            "Döner",
            "Lost",
            "Deez",
            "Small",
            "Hard",
            "Flat",
            "Drunk",
            "The",
            "Hot",
            "Flirty",
            "Sexy",
            "Naked",
            "Stripped",
            "Tied",
            "Kinky",
            "Privatversichert",
            "Gay",
            "Juicy",
            "Dirty",
            "Thirsty",
            "Handsome",
            "Good",
            "Crazy",
            "Psychic"

    };
    public String[] lastNames = {
            "Lightbulb",
            "Nightmare",
            "Dream",
            "Kitty",
            "Upgrade",
            "Markus",
            "Kampfhelikopter",
            "NNN",
            "Sub",
            "DDD",
            "DarkSoulsBoss",
            "Homie",
            "Schwanz",
            "Loch",
            "Alina",
            "OleMaartenHolftrerich",
            "Smaarten",
            "Oma Maarten",
            "Hero",
            "Lord",
            "Fantasy",
            "Pokemon",
            "Bitch",
            "Scream",
            "Oooops",
            "Smoke",
            "Döner",
            "User",
            "800 J. Holtfrerich",
            "Winner",
            "Lover",
            "Nuts",
            "Balls",
            "ThiccShady",
            "Timolia",
            "B00bs",
            "Master",
            "Niklas",
            "Tim",
            "Kevin",
            "Manuela",
            "Stella",
            "Jost",
            "Atakan",
            "Aswin",
            "Max",
            "Lukas",
            "Marvin",
            "Jonas",
            "Nick",
            "OleFanclub",
            "ErvinKotzlovski",
            "Schmonz",
            "VdV",
            "Slut",
            "Red-Light-District",
            "Juice",
            "Talk",
            "Impact",
            "Mommy",
            "Daddy",
            "Boy",
            "Girl",
            "Love",
            "Honey",
            "DM's",
            "Waifu",
            "Nordwand",
            "Wienands"
    };
}