package de.hebk;

import java.util.Random;

public class Texts {

    Random r1 = new Random();
    int r2 = r1.nextInt(14);

    String randomNames[] = {
            "Ter",
            "The",
            "Knight",
            "Shredder",
            "Zufälliger",
            "Lack",
            "Master",
            "Richtig",
            "Eins",
            "Name",
            "Element",
            "Null",
            "Keiner",
            "Echter",
            "Bester",
            "Ninja",
            "Zero",
            "Zufällig",
            "Destroyer",
            "_Laser",
            "Game",
            "Cube",
            "Core",
            "Neon",
            "Zahl",
            "Generic",
            "Funktion",
            "Code",
            "Winner",
            "Dust",
            "Nemesis",
            "Final Fantasy" + (r2 +1),
            "Terminator",
            "User",
            "Axe",
            "Lost",
            "High",
            "Java",
            "Geheim",
            "Ranger",
            "Raptor",
            "Akar",
            "Mars",
            "Rest",
            "Razor",
            "Zahl",
            "Yukin",
            "Bat",
            "Kämpfer",
            "Falle",
            "Rote",
            "Ista",
            "AusT",
            "InD_",
            "Rats",
            "Spike",
            "Klasse",
            "Abstrakte",
            "Fantasy",
            "Old School ",
            "Hero",
            "Lord",
            "Dark",
            "Void",
            "Reaper",
            "Invisible",
            "Monster",
            "Mana",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",
            "Zufälliger",

    };

}
